### ISSUE TITLE
Have to click twice here to select a package, should work in single click

### ISSUE THREAD

**Issue by nitansh11** [ramNgithub/Engagebay.com-Clone#47]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/8274883/212324344-66f0a7bd-20fb-4de3-90dc-3fd2ef336535.png">

**Comment by nitansh11** [comment]
Same double click issue here and bottom padding/margin need to be coorected
<img width="984" alt="image" src="https://user-images.githubusercontent.com/8274883/212324427-8e1a46b5-2b70-4385-a40f-81990847c580.png">

**Comment by Omchand27** [comment]
done

**Comment by Omchand27** [comment]
done
